profile: "default"
profiles:
  default:
    fourc_metadata_path: "4C_metadata.yaml"
    fourc_json_schema_path: "4C_schema.json"
    description: "Profile for the latest successful nightly 4C build"
    user_defaults_path: null
  completion_schema:
    fourc_metadata_path: "4C_metadata.yaml"
    fourc_json_schema_path: "4C_schema_completion.json"
    description: "Profile for the completion-oriented schema, which is updated nightly with the latest successful 4C build schema. Note: this schema is wraps the full schema, it hence relies on the full schema being present."
    user_defaults_path: null
  4C_docker_main:
    fourc_metadata_path: "/home/user/4C/build/4C_metadata.yaml"
    fourc_json_schema_path: "/home/user/4C/build/4C_schema.json"
    description: "Profile for the 4C docker build main"
    user_defaults_path: null
  4C_docker_main_completion_schema:
    fourc_metadata_path: "/home/user/4C/build/4C_metadata.yaml"
    fourc_json_schema_path: "/home/user/4C/build/4C_schema_completion.json"
    description: "Profile for the 4C docker build mainn for testing the completion-oriented schema."
    user_defaults_path: null
